### ISSUE TITLE
MainWindow 생성자에서 initializeWith()를 호출하면 무작위하게 hang이 걸림

### ISSUE THREAD

**Issue by unstabler** [unstabler/Azalea#8]
```
Using host libthread_db library "/usr/lib/libthread_db.so.1".
[New Thread 0x7ffff19a1700 (LWP 12670)]
[New Thread 0x7fffeb226700 (LWP 12671)]
[New Thread 0x7fffe9f3f700 (LWP 12672)]
[New Thread 0x7fffe9414700 (LWP 12673)]
[New Thread 0x7fffdbd57700 (LWP 12674)]
[New Thread 0x7fffdb556700 (LWP 12675)]
[New Thread 0x7fffd994d700 (LWP 12676)]

Thread 1 "azalea" received signal SIGSTOP, Stopped (signal).
0x00007ffff5f1097d in syscall () from /usr/lib/libc.so.6
(gdb) bt
#0  0x00007ffff5e05bac in pthread_cond_wait@@GLIBC_2.3.2 () from /usr/lib/libpthread.so.0
#1  0x00007fffd9f48304 in ?? () from /usr/lib/dri/i965_dri.so
#2  0x00007fffd9f48028 in ?? () from /usr/lib/dri/i965_dri.so
#3  0x00007ffff5dffa92 in start_thread () from /usr/lib/libpthread.so.0
#4  0x00007ffff5f15cd3 in clone () from /usr/lib/libc.so.6
```

현재는 다음과 같은 방식으로 호출하고 있음. 
```c++
MainWindow::MainWindow(...) {
    // ...
    this->initializeWith(credential);
}
```

아래와 같이 다음 틱에 호출하도록 하면 행이 걸리지 않음이 확인됨

```c++
MainWindow::MainWindow(...) {
    // ...
    QTimer::singleShot(0, [=] {
        this->initializeWith(defaultCredential);
    });
}
```

어떻게 하는게 좋지?
- 상기 방법대로 QTimer를 쓰면 뭔가 멍청해 보임 
- 이벤트 큐에 의존해서 생성자 끝에 created()같은 이벤트를 발생시켜서, 해당 이벤트가 발생되었을 때 초기화 하도록 늦춤

**Comment by unstabler** [comment]
과연 이게 문제였을까???

**Comment by unstabler** [comment]
해결된 것 같다.
